### PR TITLE
Add `on_success`, `on_failure` for `Try` class

### LINKED ISSUE #5: Add `on_success` callback to `Try` class
Add an `on_success` callback to the `Try` class, so that you can call a function w/o returning a value, when the `Try` succeeds.

### PR DESCRIPTION
**Pull request by sloboegen**
Closes #5 and #6.

### CODE REVIEW

**Comment by vickumar1981** [comment]
lgtm.  👍 .  this is awesome.

would you mind removing the `--boxed` parameter in the Makefile.  This will fix the build.

https://github.com/vickumar1981/pyeffects/blob/master/Makefile#L12

I think once that is done, I can merge this in and release a 1.0.6 version that includes your changes for Future and Try classes.

Thanks again.  @sloboegen

**Comment by sloboegen** [comment]
> lgtm. 👍 . this is awesome.
> 
> would you mind removing the `--boxed` parameter in the Makefile. This will fix the build.
> 
> https://github.com/vickumar1981/pyeffects/blob/master/Makefile#L12
> 
> I think once that is done, I can merge this in and release a 1.0.6 version that includes your changes for Future and Try classes.
> 
> Thanks again. @sloboegen

Thanks! @vickumar1981

Also, I can add `on_failure` for `Future` before v1.0.6, it seems logical.

And what do you think about migration to GitHub Action CI?

**Comment by vickumar1981** [comment]
@sloboegen , i agree with both points.

- We can wait until `on_failure` is there for the `Future` class before releasing a new release to PyPI.  It makes sense b/c you added `on_success` in a previous PR. 
- The current Travis build is failing b/c of some changes or something in the `make ci` target.  Also, I think there's a few errors in the `.rst` docs (`make readme`).  Travis used to be cool, but I'd like to move over to Github actions instead, particularly b/c the build is failing anyway.

I can go ahead and create the issues later tonight, or if you'd like to, feel free to create them in the issues section.

I'm also thinking about creating a `CONTRIBUTING.md` file to document how to use the `make` targets, and how to get setup for development, in general.

Thanks again for all your help.  The additions are great!

**Comment by sloboegen** [comment]
@vickumar1981 thanks :)
Creating `CONTRIBUTING.md` is a nice idea!

I'll create the issues and make the PRs (`on_failure` + GitHub Actions) on the current week.

**Pull request merged**
